name: Run Huoxing Script

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run huoxing.py
        run: python huoxing.py

      - name: Commit and push JSON result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p api/huoxing
          if ls *.json 1> /dev/null 2>&1; then
            mv *.json api/huoxing/
            git add api/huoxing/*.json
            git commit -m "Add daily JSON result"
            git push
          else
              echo "No JSON files found to move."
          fi
