name: Run Huoxing Script

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run huoxing.py
      run: python huoxing.py

    - name: Commit and push JSON result
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add *.json
        git commit -m "Add daily JSON result"
        git push https://github.com/${{ github.repository }}.git "HEAD:main" --token ${{ secrets.GITHUBACTIONTOKEN }}